spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/orders-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP-OrderService

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false
    baseline-on-migrate: true
    ignore-migration-patterns: "*:ignored"
    locations: classpath:db/migration

  logging:
    level:
      org:
        springframework: INFO
        hibernate.SQL: DEBUG
        hibernate.type.descriptor.sql.BasicBinder: TRACE